local ZA = ZAuras

ZA.UI = {    
    FRAME_PADDING_TOP = 50,
    FRAME_PADDING_RIGHT = 35,
    FRAME_PADDING_BOTTOM = 35,
    FRAME_PADDING_LEFT = 35,
    MAINFRAME_WIDTH = 500,
    MAINFRAME_HEIGHT = 400,    
    NEWFRAME_WIDTH = 400,
    NEWFRAME_HEIGHT = 400,
    BUTTON_HEIGHT = 25,
    BUTTON_WIDTH = 75,
    BUTTON_SPACING = 5,
    SCROLLBAR_WIDTH = 8,
    ICON_SIZE = 36,
    ICON_SPACING = 7,
    ICONS_PER_ROW = 10,
    LABEL_INPUT_SPACING = 15
}